[workspace]
members = ["ckb-std-tests", "exec-callee", "exec-caller", "exec-caller-by-code-hash", "spawn-caller", "spawn-caller-by-code-hash", "spawn-callee"]
resolver = "2"

[profile.release]
overflow-checks = true
opt-level = 's'
codegen-units = 1
