[package]
name = "exec-callee"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
native-simulator = ["ckb-std/native-simulator"]

[dependencies]
<<<<<<< HEAD
ckb-std = { path = "../../", default-features=false, features=["allocator", "build-with-clang", "calc-hash", "ckb-types", "libc"] }
=======
ckb-std = { path = "../../", features=["build-with-clang"] }
>>>>>>> b5ef88b (Preserve most of the directory structure)
